import 'dart:ui';

const secondaryColor = Color(0xffff5f5f7);
const backgroundColor = Color(0xffffffff);
const containerColor = Color(0xfff141522);
const borderColor = Color(0xfffCFD3D4);
const textColor = Color(0xfff141522);
const buttonColor = Color(0xfff5570F1);
const progressBackround = Color(0xfffE2E6F9);
const subtitleColor = Color(0xfffABAFB1);
const shadeColor = Color(0xfffCFD3D4);
const workingWidgetColor = Color(0xfffEBF9F1);
const workingTextColor = Color(0xfff1F9254);
const notWorkingWidgetColor = Color(0xfffFBE7E8);
const notWorkingTextColor = Color(0xfffA30D11);
const addNewButtonColor = Color(0xfff624DE3);
const drawerItemColor = Color(0xfff8E92BC);
const buttonShadeColor = Color(0xfffC4C4C4);
const cardShadowColor = Color(0xfffE5E7EB);
const searchBackgroundColor = Color(0xfffF9FAFB);
const dividerColor = Color(0xfffE5E7EB);
const cardHoverColor = Color(0xfffF3F4F6);
